name: Publish to NPM

on:
  workflow_run:
    workflows:
      - "CI Pipeline"
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.ref, 'refs/tags/v') &&
      github.event.workflow_run.head_branch == 'main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"

      - name: Extract version from tag
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Read current package.json version
        id: package-version
        run: echo "CURRENT_VERSION=$(node -p 'require("./package.json").version')" >> $GITHUB_ENV

      # - name: Validate tag version
      #   run: |
      #     echo "Current package.json version: $CURRENT_VERSION"
      #     echo "Git tag version: $TAG_VERSION"

      #     if [ "$(printf "%s\n%s" "$CURRENT_VERSION" "$TAG_VERSION" | sort -V | head -n1)" != "$CURRENT_VERSION" ]; then
      #       echo "✅ Tag version is valid (higher than current version)"
      #     else
      #       echo "❌ ERROR: Tag version ($TAG_VERSION) is lower than or equal to the current version ($CURRENT_VERSION)."
      #       exit 1
      #     fi

      # - name: Update package.json version
      #   run: npm version --no-git-tag-version $TAG_VERSION

      # - name: Install dependencies
      #   run: npm install

      # - name: Build package
      #   run: npm run build

      # - name: Publish to NPM
      #   run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
